## Measuring the divergence in empirical and theoretical probabilities of permutations using squared difference

$$
\Delta(a, b) = \sum_{i}(Prob(i, a) - Prob(j, a))^2
$$

In [1]:
import import_ipynb
from Mallows_Notebook import *
from PL_Notebook import *
import metropolis
import math
from tqdm import tqdm_notebook
import itertools

importing Jupyter notebook from Mallows_Notebook.ipynb
importing Jupyter notebook from PL_Notebook.ipynb
0.125
[0.30201484 0.2058898  0.27630837 0.21578699]
defaultdict(<class 'int'>, {4: 308, 3: 126, 1: 19, 2: 22})
initial weights [0.3279398  0.10113504 0.37556066 0.1953645 ]



deque([2518.2061604003343, 2567.299698085064, 2554.6195404226, 2495.811155212152, 2559.2797001553017, 2557.7745434433127, 2571.4460034928684, 2588.236059718956, 2595.9627316862643, 2594.8959694439354, 2649.940994678969, 2654.1612692255385, 2678.391640577149, 2686.2030898864427, 2681.832976776231], maxlen=15)
PL loaded


In [ ]:
import os
netflix = os.listdir('netflix_soc')
files = ['netflix_soc/' + x for x in netflix]

In [ ]:
irish = [#'ED-00001-00000001.soi',\
         'ED-00001-00000002.soi',\
         #'ED-00001-00000003.soi',]
        ]

files = ['irish_soi/' + x for x in irish]

In [2]:
files = ['ED-00002-00000001.soi',\
         'ED-00002-00000002.soi',\
         'ED-00002-00000003.soi',\
         'ED-00002-00000004.soi',\
         'ED-00002-00000005.soi',\
         'ED-00002-00000006.soi',\
         'ED-00002-00000007.soi',\
         'ED-02-Logo.soi']

files = ['preflib_soi/' + x for x in files]
files

['preflib_soi/ED-00002-00000001.soi',
 'preflib_soi/ED-00002-00000002.soi',
 'preflib_soi/ED-00002-00000003.soi',
 'preflib_soi/ED-00002-00000004.soi',
 'preflib_soi/ED-00002-00000005.soi',
 'preflib_soi/ED-00002-00000006.soi',
 'preflib_soi/ED-00002-00000007.soi',
 'preflib_soi/ED-02-Logo.soi']

In [ ]:
files = ['preflib_soi/ED-02-Logo.soi']

In [35]:
# The BIG run
import os
bigrun = os.listdir('all_soi')
soi_files = ['all_soi/' + x for x in bigrun]

u10 = []
u11 = []
for file in soi_files:
    cands, lengths, num_votes, votes = readPreflib.soiInputwithNumVotes(file)
    complete = True
    if len(cands) != len(lengths.keys()):
        complete = False
    if len(cands) < 10 and complete:
        u10.append(file)
#     if len(cands) < 11:
#         u11 += 1

# u10 = u10[9:]
# u10 = u10[:8]
u10

['all_soi/ED-00001-00000002.soi',
 'all_soi/ED-00002-00000001.soi',
 'all_soi/ED-00002-00000002.soi',
 'all_soi/ED-00002-00000003.soi',
 'all_soi/ED-00002-00000004.soi',
 'all_soi/ED-00002-00000005.soi',
 'all_soi/ED-00002-00000006.soi',
 'all_soi/ED-00002-00000007.soi',
 'all_soi/ED-00002-00000008.soi',
 'all_soi/ED-00008-00000001.soi',
 'all_soi/ED-00008-00000010.soi',
 'all_soi/ED-00008-00000012.soi',
 'all_soi/ED-00008-00000014.soi',
 'all_soi/ED-00008-00000015.soi',
 'all_soi/ED-00008-00000017.soi',
 'all_soi/ED-00008-00000018.soi',
 'all_soi/ED-00008-00000020.soi',
 'all_soi/ED-00028-00000001.soi',
 'all_soi/ED-00028-00000002.soi',
 'all_soi/ED-00028-00000003.soi',
 'all_soi/ED-00028-00000004.soi',
 'all_soi/ED-00028-00000005.soi',
 'all_soi/ED-00028-00000006.soi',
 'all_soi/ED-00028-00000007.soi',
 'all_soi/ED-00028-00000008.soi',
 'all_soi/ED-00028-00000009.soi',
 'all_soi/ED-00028-00000010.soi',
 'all_soi/ED-00028-00000011.soi',
 'all_soi/ED-00028-00000012.soi',
 'all_soi/ED-0

In [29]:
list_of_votes = []
mallows_params = []
pl_params = []

nruns = 5_000

# print(files[0])

print('Projected Time =',143/50.0 * nruns,'seconds, which is ~', 30/1000.0 * nruns, 'minutes')
for file in tqdm_notebook(u10, desc = 'All Files'):
    # print(file)
    cands, lengths, num_votes, votes = readPreflib.soiInputwithNumVotes(file)
    num_alternatives = len(cands)
    #print(num_alternatives)
    #print(num_votes)
    #print(list(lengths.keys()))
    list_of_votes.append((num_votes, lengths, votes))
    # print(list_of_votes[0])
    p_mal = runMallows(votes, num_alternatives, nruns, lengths)
    mallows_params.append(p_mal)
    p_pl = runPL(votes, nruns, lengths)
    pl_params.append(p_pl)

Projected Time = 14300.0 seconds, which is ~ 150.0 minutes


stopped after  94
deque([1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918, 1461.392631137918], maxlen=15)
defaultdict(<class 'int'>, {1: 0.25130434782608696, 2: 0.2108695652173913, 3: 0.21753623188405796, 4: 0.16144927536231884, 5: 0.0463768115942029, 9: 0.07942028985507246, 7: 0.005797101449275362, 6: 0.02072463768115942, 8: 0.006521739130434782, 0: 0})
initial weights [0.04478802 0.03921405 0.00544811 0.04808484 0.06353734 0.06066137
 0.20786799 0.22852714 0.30187115]


deque([242.71849779622502, 242.70839704012403, 242.61691344738446, 242.5424418048822, 242.4947478684619, 242.58864670730452, 242.8795215776017, 243.51307659766178, 243.49804679205425, 243.3601216813386, 243.8301416603849, 243.58671116840122, 243.4899935071771, 243.51493411696705, 243.60284756831618], maxlen=15)


stopped after  1118
deque([2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303, 2083.3822270037303], maxlen=15)
defaultdict(<class 'int'>, {1: 0.23600552868002764, 3: 0.3214697074406819, 2: 0.1422483298779083, 4: 0.1529601474314674, 5: 0.035245335176226675, 9: 0.08880442294402212, 8: 0.005413499193734163, 6: 0.012554710896106889, 7: 0.005298318359824925, 0: 0})
initial weights [0.06952365 0.06106911 0.03866189 0.12841019 0.01429481 0.0219702
 0.21934648 0.18990682 0.25681685]


deque([239.36074515762138, 238.3464022947685, 238.09198550023862, 237.91062073050412, 237.44655362505796, 237.11090639274863, 237.37046345587544, 237.36365969794338, 237.303958254794, 237.38679399479093, 237.2626473342217, 237.4449520470864, 237.43324712421625, 237.44951218570245, 237.43867697998607], maxlen=15)


stopped after  1037
deque([1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898, 1321.3747865348898], maxlen=15)
defaultdict(<class 'int'>, {1: 0.20762802656953075, 2: 0.23184058281551317, 3: 0.233983286908078, 4: 0.15856010284979644, 8: 0.10531390614956075, 5: 0.0432826226698093, 6: 0.013284765373901865, 7: 0.006106706663809728, 0: 0})
initial weights [0.02554838 0.02459545 0.04155341 0.0827931  0.06910992 0.2213617
 0.21737423 0.31766382]


deque([319.45915578723384, 319.4088871093089, 319.32907131317563, 320.2073969375261, 321.09650783865993, 321.00923122663505, 321.61800328050487, 321.4439603947462, 320.4292340857812, 320.25254762891615, 319.1617883384472, 319.4036696802128, 320.40268557901055, 320.3346409055351, 320.3372538795689], maxlen=15)


stopped after  376
deque([2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745, 2385.961185284745], maxlen=15)
defaultdict(<class 'int'>, {1: 0.2435107564892435, 2: 0.23886476113523886, 3: 0.22361377638622362, 4: 0.14897485102514899, 8: 0.10130289869710131, 5: 0.02918897081102919, 6: 0.007675992324007676, 7: 0.006867993132006868, 0: 0})
initial weights [0.02100581 0.01899788 0.02492011 0.05110541 0.05672758 0.11864418
 0.25857674 0.45002229]


deque([408.77395737696094, 408.6679208957001, 409.3534341174679, 409.02244352195106, 408.69346906802224, 408.37270530518464, 408.66125094242955, 408.582213962935, 408.54337591976815, 408.5329505142582, 408.5677571979717, 407.1475016966415, 406.77355243374654, 406.0290847822092, 405.1229959671183], maxlen=15)


stopped after  792
deque([1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746, 1976.644853743746], maxlen=15)
defaultdict(<class 'int'>, {2: 0.25583545181419, 1: 0.24000462214005083, 3: 0.223249364455743, 4: 0.1509128726600416, 5: 0.03547492489022418, 9: 0.06655881673214699, 6: 0.014097527155072799, 8: 0.008319852091518374, 7: 0.005546568061012249, 0: 0})
initial weights [0.07162657 0.03935966 0.04996177 0.01322019 0.08762523 0.13583694
 0.04386445 0.26029428 0.2982109 ]


deque([378.35031651819816, 377.99815217452624, 377.5243950930522, 377.50732121067784, 377.4573241641672, 377.4351163118371, 376.59393489334343, 376.51275999319, 377.53553575677256, 378.5703478233859, 377.4220859925677, 377.1886025285528, 377.5035603338977, 376.7316089335835, 376.6754560537024], maxlen=15)


stopped after  204
deque([1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594, 1615.1296612224594], maxlen=15)
defaultdict(<class 'int'>, {1: 0.19695543000627747, 2: 0.2405053358443189, 3: 0.24144695543000627, 4: 0.1746704331450094, 5: 0.04770872567482737, 9: 0.0709353421217828, 6: 0.016242937853107344, 8: 0.0045511613308223476, 7: 0.006983678593848085, 0: 0})
initial weights [0.0406574  0.03708796 0.00276465 0.00943863 0.08457463 0.15335306
 0.12947953 0.09340015 0.44924399]


deque([451.2274007513951, 451.84775222226193, 451.54102885287836, 451.5638199071742, 452.4964748625616, 451.5331588234789, 451.09710133157824, 450.31493592414006, 449.1216361873097, 448.75298517357623, 449.45625549145024, 450.18884092032283, 450.1474159514422, 451.01776387259554, 451.0520182220203], maxlen=15)


stopped after  55
deque([1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028, 1896.460509353028], maxlen=15)
defaultdict(<class 'int'>, {1: 0.30615657991010764, 2: 0.18386118950559213, 3: 0.23047977422389465, 4: 0.14205079962370648, 5: 0.038883662590153655, 9: 0.07410891606564231, 8: 0.006062506532873419, 6: 0.013379324762203408, 7: 0.005017246785826278, 0: 0})
initial weights [0.03025419 0.01706623 0.03226513 0.07341649 0.04253632 0.02128432
 0.21663392 0.2651145  0.3014289 ]


deque([358.0343911221313, 357.9993483690067, 358.08013069603646, 357.95873776342705, 357.95013619170254, 357.09149064679974, 356.9077206535719, 357.75578990671943, 358.421615035414, 358.56668870192397, 357.6972957741706, 356.8183286877191, 356.8704426987623, 356.3182856457828, 356.2698364798358], maxlen=15)


stopped after  93
deque([2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427, 2291.883251201427], maxlen=15)
defaultdict(<class 'int'>, {1: 0.25028610666056306, 3: 0.28633554589150834, 2: 0.17360952162966353, 4: 0.14602883955138476, 9: 0.07862211032272831, 5: 0.04005493247882811, 6: 0.015106431677729458, 8: 0.004463263904783703, 7: 0.005493247882810712, 0: 0})
initial weights [0.04629577 0.04588879 0.03373506 0.03054067 0.1020307  0.07202173
 0.23093086 0.2430361  0.19552033]


deque([282.39467778111623, 282.4551679592222, 282.6297142991159, 282.2092752346396, 282.21933167265496, 282.2106132999239, 282.46581772665144, 281.12440908501014, 281.15985744620195, 280.8709526884568, 280.4413104104735, 281.0810558828179, 281.25635931682837, 280.7376030547887, 280.9055160091895], maxlen=15)


In [30]:
mallows_params, pl_params
pickle.dump([mallows_params, pl_params], open('pickle/u10_28_5k.p','wb'))
# prob pickle things here
mallows_params, pl_params
# print(pl_params[2])
# mallows_params.pop(2)

([[array([3, 6, 8, 5, 1, 7, 4, 2, 9]), 0.002517998703411961],
  [array([9, 4, 5, 8, 3, 7, 2, 1, 6]), 0.0006146129814220413],
  [array([1, 4, 2, 8, 7, 5, 6, 3]), 0.00017515828370942566],
  [array([7, 8, 2, 6, 3, 1, 5, 4]), 0.0010341632271258783],
  [array([4, 3, 9, 6, 1, 5, 8, 2, 7]), 0.0014362817086728263],
  [array([2, 9, 7, 8, 6, 1, 4, 5, 3]), 5.6681369158761985e-05],
  [array([6, 3, 7, 4, 1, 8, 9, 2, 5]), 0.008013644303874662],
  [array([9, 4, 6, 8, 5, 1, 7, 2, 3]), 0.0009473147827070705]],
 [array([0.06658622, 0.12265479, 0.09405724, 0.07447783, 0.09679563,
         0.10078141, 0.16521486, 0.172877  , 0.10655501]),
  array([0.10292062, 0.10321315, 0.15874575, 0.1089393 , 0.10436468,
         0.1006994 , 0.11121339, 0.08793239, 0.12197131]),
  array([0.14559781, 0.14542865, 0.12626349, 0.14756259, 0.08033008,
         0.0998198 , 0.13258328, 0.12241429]),
  array([0.13157881, 0.10885867, 0.13273439, 0.13601211, 0.08735751,
         0.05516434, 0.15572035, 0.19257382]),
  array([0.07

In [31]:
def all_possible_votes(n):
    all_votes = []
    for i in range(1,n+1):
        # print(i)
        sub = list(itertools.permutations(range(1,n+1),i))
        #sub = itertools.permutations(range(1,i+1))
        for p in sub:
            all_votes.append(p)
    return all_votes
# import sys
len(all_possible_votes(8))

109600

In [32]:
_,_,temp = list_of_votes[0]
known = [tuple(x) for x in list(zip(*temp))[1]]
pos = all_possible_votes(5)
len(pos)
# [x for x in pos if x not in known]
# len(known)
list_of_votes

[(6900,
  defaultdict(int,
              {1: 0.25130434782608696,
               2: 0.2108695652173913,
               3: 0.21753623188405796,
               4: 0.16144927536231884,
               5: 0.0463768115942029,
               9: 0.07942028985507246,
               7: 0.005797101449275362,
               6: 0.02072463768115942,
               8: 0.006521739130434782,
               0: 0}),
  [(476, [7]),
   (389, [8]),
   (304, [3]),
   (299, [3, 8]),
   (263, [8, 3]),
   (174, [2]),
   (149, [1]),
   (119, [6]),
   (82, [7, 1]),
   (73, [1, 6]),
   (67, [6, 1]),
   (53, [5]),
   (49, [9]),
   (42, [7, 6]),
   (39, [7, 1, 6]),
   (39, [7, 5]),
   (33, [3, 8, 1]),
   (31, [7, 5, 1]),
   (31, [8, 7]),
   (28, [1, 6, 7]),
   (27, [8, 3, 6]),
   (26, [7, 5, 9]),
   (26, [8, 3, 1]),
   (25, [1, 7]),
   (25, [6, 7]),
   (24, [3, 7]),
   (23, [2, 1]),
   (23, [3, 8, 6]),
   (22, [7, 3]),
   (21, [6, 7, 1]),
   (21, [2, 4]),
   (21, [4]),
   (21, [6, 3, 8]),
   (20, [3, 6, 8]),
   (20,

In [6]:
import collections
#collections.OrderedDict(sorted(list_of_votes[0][1]))
def default_to_sorted(dictdict):
    lens_dict = dictdict
    od = collections.OrderedDict(sorted(lens_dict.items()))
    if 0 in od:
        del(od[0])
    return od

In [33]:
def squaredDif(a, b):
#     if a == 0 and b == 0:
#         return 0
#     if a != 0:
#         a = math.log(abs(a))

    # a = math.log(a)
    return (a - b)**2

table = []
col_names = ['Number_Votes','Mallow\'s_Divergence','Plackett-Luce_Divergence']

for i in tqdm_notebook(range(len(list_of_votes))):
    num_votes, lengths, votes = list_of_votes[i]
    print(num_votes)
    lengths = default_to_sorted(lengths)
    num_alternatives = len(lengths)
    sigma, phi = mallows_params[i]
    pl_weights = pl_params[i]
    
    delta_mallows = 0
    delta_plackett = 0
       
    freq_list = list(zip(*votes))[0]
    known_votes = [tuple(x) for x in list(zip(*votes))[1]]
    # possibles = all_possible_votes(num_alternatives)
    # empirical_zero = [x for x in possibles if x not in known_votes]
    vote_in = 0
    for vote in tqdm_notebook(all_possible_votes(num_alternatives)):
        if (vote in known_votes):
            vote_in += 1
            index = known_votes.index(vote)
            num_occurances = freq_list[index]
            
            empirical = num_occurances / num_votes
            mallows = mallowsProb(vote, sigma, phi)
            plackett = probPlackett(vote, pl_weights)
            delta_mallows += squaredDif(mallows, empirical)
            delta_plackett += squaredDif(plackett, empirical)
            # print(vote)
        else:
            empirical = 0
            mallows = mallowsProb(vote, sigma, phi)
            plackett = probPlackett(vote, pl_weights)
            # print(mallows, plackett)
            delta_mallows += squaredDif(mallows, empirical)
            delta_plackett += squaredDif(plackett, empirical)
    print(vote_in)
#     for entry in votes:
#         num_occurances, vote = entry
#         empirical = num_occurances / num_votes
#         mallows = mallowsProb(vote, sigma, phi)
#         plackett = probPlackett(vote, pl_weights)
#         delta_mallows += squaredDif(mallows, empirical)
#         delta_plackett += squaredDif(plackett, empirical)
    
    table.append([num_votes, delta_mallows, delta_plackett])

6900


2031
8682


2197
9334


2156
9901


2226
8654


2114
12744


2831
9567


2367
8738


2172


In [34]:
import pandas as pd

npdata = np.array(table)
results_df = pd.DataFrame(data=npdata,columns=col_names)
results_df.index += 1
# pickle.dump(results_df, open('pickle/divergence10k.p','wb'))
results_df

Number_Votes  Mallow's_Divergence  Plackett-Luce_Divergence
1        6900.0         28241.038542                 50.404369
2        8682.0         30140.875207                 47.690520
3        9334.0         15228.450599                 35.152489
4        9901.0         14887.191457                 37.450739
5        8654.0         29305.686858                 48.567345
6       12744.0         30721.945313                 76.856822
7        9567.0         23401.130750                 47.750907
8        8738.0         29799.859947                 61.462438

In [ ]:
perms = list(itertools.permutations([1,2,3]))
print(perms)
(1,2,3) in perms

In [ ]:
pickle.dump([mallows_params, pl_params, table], open('./pickle/ireland_0001_table_10k.p', 'wb'))

In [ ]:
mallows_params

In [ ]:
pl_params

In [37]:
mallows_debian = [122.55,178.23,2893.52,4990.13,207.46,476.65,197.95,101.64]
plackett_debian = [7.68,12.24,26.22,36.26,50.27,12.20,7.78,35.42]
num_alternatives = [4,5,7,8,9,5,4,8]

def AIC(likelihood, k):
    return (-2 * math.log(likelihood)) + (2*k)

for l in mallows_debian:
    aic = AIC(l, 2)
    print(l,"\t","%2.2f"%aic)

# for i in range(len(plackett_debian)):
#     l = plackett_debian[i]
#     aic = AIC(l, num_alternatives[i])
#     print(l,"\t","%2.2f"%aic)

122.55 	 -5.62
178.23 	 -6.37
2893.52 	 -11.94
4990.13 	 -13.03
207.46 	 -6.67
476.65 	 -8.33
197.95 	 -6.58
101.64 	 -5.24


In [38]:
def BIC(likelihood, k, n):
    return k*math.log(n) - 2*math.log(likelihood)

# for i in range(len(mallows_debian)):
#     l = mallows_debian[i]
#     k = 2
#     n = len(all_possible_votes(num_alternatives[i]))
#     bic = BIC(l, k, n)
#     print(l,'\t','%2.2f'%bic)
    
for i in range(len(plackett_debian)):
    l = plackett_debian[i]
    k = num_alternatives[i]
    n = len(all_possible_votes(num_alternatives[i]))
    bic = BIC(l, k, n)
    print(l,'\t','%2.2f'%bic)

7.68 	 12.56
12.24 	 23.91
26.22 	 60.14
36.26 	 85.66
50.27 	 116.38
12.2 	 23.92
7.78 	 12.53
35.42 	 85.70


In [ ]:
my_list = []
my_list.append(5.3)

# del(my_list)
my_list.clear()
my_list

In [55]:
PL_APAUK = [55.48,7.68,12.24,26.22,36.26,50.27,12.2,7.78,35.42,12.37,12.26,12.11,12.01,12.03,11.98,12.27,12.17,12.17,12.03,12.17,12.15,11.99,50.40,47.69,35.15,37.45,48.57,76.86,47.75,61.46]




bic_li = []
aic_li = []

for i in range(len(PL_APAUK)):
    l = PL_APAUK[i]
    k = 5# num_alternatives[i]
    n = len(all_possible_votes(k))
    bic = BIC(l, k, n)
    bic_li.append(bic)
    aic = AIC(l, k)
    aic_li.append(aic)
    
bic_li

[20.88708072075542,
 24.841886817329524,
 23.909707357480325,
 22.38608095497758,
 21.737695500995276,
 21.084308956239717,
 23.916254008170263,
 24.816013235268084,
 21.78457264693931,
 23.88857753883989,
 23.906442050632556,
 23.93106279651868,
 23.9476466394649,
 23.94431885167551,
 23.952648726274077,
 23.904811394203044,
 23.921178097649815,
 23.921178097649815,
 23.94431885167551,
 23.921178097649815,
 23.92446757207557,
 23.95097997356984,
 21.07914356149404,
 21.189682447028417,
 21.799876675135337,
 21.67311249172223,
 21.153113798933376,
 20.23515474137529,
 21.187167777795207,
 20.682352798244008]